POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcnNpODgiLCJpZCI6IjY5OTQ0ZWMyYjViMzg0ZTIwZTA5YjQ2NiIsImlhdCI6MTc3MTMyNzcxMX0.3oNge_hU3VYwXYpijNLfn_LXn24IJylH75maYotFaxA

{
    "title" : "Kirsin viikonloppu",
    "author" : "Kirsi Huttunen",
    "url": "http://kirsinblog.com/kirsinviikonloppu",
    "likes": 2342344
}